In [1]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
df_plano_saude = pd.read_csv(r'C:\Users\vitor\machine_learning\bases_dados\plano_saude.csv')
df_plano_saude

idade  custo
0     18    871
1     23   1132
2     28   1242
3     33   1356
4     38   1488
5     43   1638
6     48   2130
7     53   2454
8     58   3066
9     63   4090

In [4]:
df_plano_saude.corr()

idade    custo
idade  1.00000  0.93092
custo  0.93092  1.00000

In [29]:
df2_plano_saude = pd.DataFrame(df_plano_saude)

In [35]:
df2_plano_saude.loc[~(df2_plano_saude.idade.astype(str).str.contains("18", regex = True, na=False))]

idade  custo
1     23   1132
2     28   1242
3     33   1356
4     38   1488
5     43   1638
6     48   2130
7     53   2454
8     58   3066
9     63   4090

In [5]:
X_idade = df_plano_saude.iloc[:, 0].values
X_idade

array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63])

In [6]:
Y_custo = df_plano_saude.iloc[:, 1].values
Y_custo

array([ 871, 1132, 1242, 1356, 1488, 1638, 2130, 2454, 3066, 4090])

In [7]:
X_idade.shape

(10,)

In [8]:
#transformar em  matriz para treinar
X_idade.reshape(-1,1)

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [10]:
X_idade = X_idade.reshape(-1,1)
X_idade.shape

(10, 1)

In [13]:
from sklearn.linear_model import LinearRegression
regressor_plano_saude = LinearRegression()
regressor_plano_saude.fit(X_idade, Y_custo.reshape(-1,1))


#quando ffor  fzr o fit - vc pode transformar os dois em matrizes

LinearRegression()

In [15]:
previsoes = regressor_plano_saude.predict(X_idade)
previsoes

array([[ 554.67272727],
       [ 864.01212121],
       [1173.35151515],
       [1482.69090909],
       [1792.03030303],
       [2101.36969697],
       [2410.70909091],
       [2720.04848485],
       [3029.38787879],
       [3338.72727273]])

In [16]:
regressor_plano_saude.intercept_ + regressor_plano_saude.coef_ * 40 #40 seria a idade q quero prever

array([[1915.76606061]])

In [14]:
X_idade

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [18]:
X_idade.ravel()

array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63])

In [19]:
Y_custo

array([ 871, 1132, 1242, 1356, 1488, 1638, 2130, 2454, 3066, 4090])

In [20]:
regressor_plano_saude.predict([[40]])

array([[1915.76606061]])

In [27]:
grafico = px.scatter(x = X_idade.ravel(), y = Y_custo)
grafico.add_scatter(x = X_idade.ravel(), y = previsoes, name = 'Regressão')
grafico.write_html('grafico.html')